name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # كل نهار مرة
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: othmane005
          outputs: dist/github-contribution-grid-snake.svg
      - name: Push generated snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
